<?php
    $theme = $services->get('theme');
    $facebook = $services->get('facebook');
    $urler = $services->get('urler');
    $request = $services->get('request');
    $canonicalUrl = $urler->generate('frontendScribbleDetail', array('slug' => $scribble->getSlug()), true);
?>

<!doctype html>
<?php echo $view->render('frontend/_partials/html.phtml'); ?>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><?php echo $scribble->getTitle(); ?></title>
        <meta name="description" content="<?php echo implode(' ', $scribble->getTags()->toArray()); ?>">
        <meta name="description" content="<?php echo htmlspecialchars($scribble->getLede(), ENT_COMPAT); ?>">
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="<?php echo $theme->getMediaPath(); ?>/styles/site/css/frontend/global.css">
        <?php echo $view->render('frontend/_partials/modernizr.phtml', array('mediaPath' => $theme->getMediaPath())); ?>
        <?php echo $view->render('frontend/_partials/icons.phtml', array('mediaPath' => $theme->getMediaPath())); ?>
        <?php echo $view->render('frontend/_partials/highlight.phtml'); ?>
    </head>
    <body>
        <?php echo $view->render('frontend/_partials/chrome-frame.phtml'); ?>
    
        <div id="top">
            <?php
                echo $view->render(
                    'frontend/_partials/top.phtml',
                    array(
                        'theme' => $theme,
                        'urler' => $urler,
                        'request' => $request
                    )
                );
            ?>
        </div>
    
        <div role="main" id="content" class="page-content">
            <article class="full-scribble">
                <?php if(!$scribble->isPublished()): ?>
                    <div class="scribbled-not-published">Not published</div>
                <?php endif; ?>
                
                <h1 class="main-title"><?php echo $scribble->getTitle(); ?></h1>
            
                <div class="scribbled-scribble-data">
                    <?php echo $scribble->getContent(); ?>
                </div>
            </article>
        </div>
    
        <div id="bottom">
            <?php
                echo $view->render(
                    'frontend/_partials/bottom.phtml',
                    array(
                        'theme' => $theme,
                        'urler' => $urler
                    )
                );
            ?>
        </div>

        <?php echo $view->render('frontend/_partials/analytics.phtml', array('id' => $services->get('google')->getItem('analyticsId'))); ?>
    </body>
</html>