<div class="bar"></div>

<footer class="scribbled-site-footer">
    <p>Get <a href="http://github.com/sirprize/scribbled">Scribbled</a> and start scribblin'</p>
    <p>
        <a href="http://github.com/sirprize/scribbled">
            <img src="<?php echo $theme->getMediaPath(); ?>/images/invertocat.png" width="32" height="32" alt="Get Scribbled on Github" />
        </a>
    </p>
    <p>&copy; <?php echo date('Y'); ?> <a href="http://sirprize.me">Christian Hoegl</a></p>
</footer>