<?php
    $findParam = $theme->getItem('findParam', 'find');
    $route = $request->attributes->get('_route');
    
    $aboutUrl = $urler->generate('frontendPageIndex', array('slug' => 'about'));
    $classScribbles = ($route == 'frontendScribbleIndex' || $route == 'frontendScribbleDetail' || $route == 'frontendScribbleTag') ? 'on' : 'off';
    $classTags = ($route == 'frontendTagIndex') ? 'on' : 'off';
    $classAbout = ($route == 'frontendPageIndex' && $request->getPathInfo() == $aboutUrl) ? 'on' : 'off';
?>

<div class="scribbled-about">
    <?php echo htmlspecialchars($theme->getItem('headerAboutText')); ?>
</div>

<div class="site-nav">
    <div class="scribbled-site-nav">
        <ul>
            <li class="first <?php echo $classScribbles; ?>">
                <a href="<?php echo $urler->generate('frontendScribbleIndex'); ?>">Scribbles<span>( )</span></a>
            </li>
            
            <li class="<?php echo $classTags; ?>">
                <a href="<?php echo $urler->generate('frontendTagIndex'); ?>">Tags<span>( )</span></a>
            </li>
            
            <li class="last <?php echo $classAbout; ?>">
                <a href="<?php echo $aboutUrl; ?>">About<span>( )</span></a>
            </li>
        </ul>
    </div>

    <div class="scribbled-site-search">
        <form method="get" action="<?php echo $urler->generate('frontendScribbleIndex'); ?>">
            <fieldset>
                <input type="text" name="<?php echo $findParam; ?>" value="<?php echo strip_tags($request->query->get($findParam)); ?>" />
            </fieldset>
        </form>
    </div>
</div>